# 端口与日志
server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      enabled: true
      request-attributes-enabled: true
      directory: logs
      pattern: commonopen
logging:
  file: logs/pay.log
  level: debug
info:
  version: @project.version@

# 应用信息
spring:
  jackson:
    serialization: true
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: TIMES-PAY
# HTTP
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      max-file-size: 10Mb
  mandatory-file-encoding: UTF-8
# 数据库
  datasource:
    url: jdbc:oracle:thin:@10.10.10.10:1522:EE   # 测试
    username: 123456
    password: 123456
# 缓存
  redis:
    database: 1
    host: 10.10.10.10
    port: 6379
    password:
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 0
  cache:
    type: redis

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.linlibang.pay.module

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true
  default-count: false
# swagger 配置
swagger:
  enable: true
  context-path:
# 关闭安全验证
management:
  security:
    enabled: false


#银联配置
unionPay:
  domainName: http://58.247.0.18:29015
  notifyUrl: http://times-pcs.linli580.com.cn/pcs/unionPay/asyncNotify  #支付结果通知url
  msgSrcId: 1017 #银联来源编号（银商分配）
  #  B扫C账号
  appId: f0ec96ad2c3848b5b810e7aadf369e2f
  appKey: 775481e2556e4564985f5439a5e6a277
  mid: 123456789900081
  tid: "00810001"
  #  C扫B账号
  #  tid: 38557688  #终端号
  #  mid: 898340149000035 #商户号
  #  appId: 10037ca764636bbc01647d1ef4e10009
  #  appKey: 389d830dcc0c46a58b0ea1962041e497 
  api:
    b2c: #商户扫客户（B扫C）
      activeTerminal: /v2/poslink/transaction/activeterminal #激活终端
      pay: /v2/poslink/transaction/pay  #支付
      voidPayment: /v2/poslink/transaction/voidpayment #支付撤销（当天）
      refund: /v2/poslink/transaction/refund #交易退款(隔天)
      query: /v2/poslink/transaction/query #订单查询
    c2b: #客户扫商户（C扫B）
      INST_MID: QRPAYDEFAULT #业务编码
      getQrCode: /v1/netpay/bills/get-qrcode #获取二维码
      closeQrCode: /v1/netpay/bills/close-qrcode #关闭二维码
      queryBill: /v1/netpay/bills/query #查询订单
      refundBill: /v1/netpay/bills/refund #退款
    h5:
      INST_MID: H5DEFAULT #业务编码
      payByTrade: /v1/netpay/trade/h5-pay #支付宝H5
      payByQmf: /v1/netpay/qmf/h5-pay #银联在线无卡
      payByUac: /v1/netpay/uac/order #银联云闪付


